const data=[
        {
            id:1,
            title:'project1',
            language:'c',
            image:'../img/workree.png'
        },
        {
            id:2,
            title:'project2',
            language:'c++',
            image:'../img/workree.png'
        },
        {
            id:3,
            title:'project1',
            language:'css',
            image:'../img/workree.png'
        },
        {
            id:4,
            title:'project1',
            language:'html',
            image:'../img/workree.png'
        },
        {
            id:5,
            title:'project1',
            language:'javascript',
            image:'../img/workree.png'
        },
        {
            id:6,
            title:'project1',
            language:'javascript',
            image:'../img/workree.png'
        },
        {
            id:7,
            title:'project1',
            language:'html',
            image:'../img/workree.png'
        },
        {
            id:8,
            title:'project1',
            language:'javascript',
            image:'../img/workree.png'
        },
        {
            id:9,
            title:'project1',
            language:'c++',
            image:'../img/workree.png'
        }
    ]
export default data;